<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UIOK9AL" failures="1" tests="1" name="Test heading" time="5.517" errors="0" timestamp="2021-11-12T22:11:26 IST">
  <testcase classname="Framework.Automation.ValidateHeading" name="basePageNavigation" time="0.508">
    <failure type="java.lang.AssertionError" message="expected [Get back to growth with the world’s #1 CRM, powered by Customer 360] but found [Get back to growth with the world’s #1 CRM, powered by Customer 360.]">
      <![CDATA[java.lang.AssertionError: expected [Get back to growth with the world’s #1 CRM, powered by Customer 360] but found [Get back to growth with the world’s #1 CRM, powered by Customer 360.]
at Framework.Automation.ValidateHeading.basePageNavigation(ValidateHeading.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- basePageNavigation -->
</testsuite> <!-- Test heading -->
